language: scala

jdk: oraclejdk8

matrix:
  fast_finish: true
  allow_failures:
  - env: SBT_CMD="mimaReportBinaryIssues"

env:
  - SBT_CMD="scalafmtSbtCheck scalafmtCheck test:scalafmtCheck scalastyle test:scalastyle"
  - SBT_CMD="coverage +test coverageReport coverageAggregate"
  - SBT_CMD="mimaReportBinaryIssues"

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt $SBT_CMD

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - flatmap-squad@spotify.com
